on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v4

      - run: yarn install
      - run: yarn build
